baseURL = "https://adamcarrier.com/"
languageCode = "en-us"
theme = "hyde"
title = "Adam Carrier"

disqusShortname = "adamcarrier"
googleAnalytics = "UA-136788226-1"

[params]
	layoutReverse = true
	theme = "hyde"
	themeColor = ""