baseURL = "https://adamcarrier.com/"
languageCode = "en-us"
theme = "hyde"
title = "Adam Carrier"
[params]
disqusShortname = ""
googleAnalytics = ""
layoutReverse = true
theme = "hyde"
themeColor = "theme-base-0d"
