baseURL = "https://adamcarrier.com/"
languageCode = "en-us"
theme = "hyde"
title = "Adam Carrier"

[params]
	disqusShortname = "adamcarrier"
	googleAnalytics = "UA-136788226-1"
	layoutReverse = true
	theme = "hyde"
	themeColor = ""