---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Hyde
- path: content
  label: Pages
  create: all
  # Imported pages without a FMT assigned
  # will automatically use "pages"
- path: content/posts
  label: Posts
  create: all
  # use the "templates" parameter to control
  # which templates can be used for new content
  # in this section. First listed template
  # is the default option.
  templates:
  - posts
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_command: hugo -E -F -D -b $DEPLOY_URL -d public
  publish_command: hugo -d public
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.42
  publish_env:
  - HUGO_ENV=production
  - HUGO_VERSION=0.42
  preview_output_directory: public
  output_directory: public
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: '0.52'
